-- Migration 022: Add conversation_summary column to chat_sessions
-- Supports hybrid memory: rolling summary + immediate window
-- Generated by the rolling summary cron (homeai-assis)

ALTER TABLE chat_sessions
ADD COLUMN IF NOT EXISTS conversation_summary TEXT DEFAULT NULL;

ALTER TABLE chat_sessions
ADD COLUMN IF NOT EXISTS summary_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

-- Index for efficient cron queries (only sessions that need summary refresh)
CREATE INDEX IF NOT EXISTS idx_conv_sessions_summary_updated
    ON chat_sessions (summary_updated_at NULLS FIRST);

COMMENT ON COLUMN chat_sessions.conversation_summary IS
    'Rolling LLM-generated summary of the full conversation history. Updated by generate_rolling_summaries cron 2x/day.';

COMMENT ON COLUMN chat_sessions.summary_updated_at IS
    'Timestamp of last summary generation. NULL means no summary has been generated yet.';
